steps:
- name: ubuntu
  script: echo hello
#- name: node
#  entrypoint: npm
#  args: ['list']
#- name: maven:3-jdk-8
#  entrypoint: mvn
#  args: ['install']  
- name: node
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install -g anypoint-cli-v4
