steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: Get setting.xml
    args: ['cp', 'gs://mule-artifact/maven/settings.xml', 'custom-settings.xml']

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Get DockerFile
    args: ['cp', 'gs://mule-artifact/maven/DockerFile', 'DockerFile']

  # The maven.repo.local setting was key
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['-Dmaven.repo.local=/workspace/.m2/repository', '--settings', 'custom-settings.xml', 'install', "-DskipTests=true"]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--build-arg', 'apiName=$TRIGGER_NAME', '--build-arg', 'workerSize=0.1', '--build-arg', 'runtime=4.4.0', '--build-arg', 'workers=1', '--build-arg', 'enviroment=STAGING' , '--build-arg', 'override=true', '-f', 'DockerFile', '.' ]

artifacts:
  objects:
    location: 'gs://europe-west3-maven.pkg.dev/third-being-207111/mule'
    location: 'gs://mule-artifact'
    paths: ['/workspace/target/*.jar']
