steps:
- name: ubuntu
  script: echo hello
#- name: node
#  entrypoint: npm
#  args: ["install", "-g", "anypoint-cli-v4"]
- name: 'faizsiegeln/anypoint-cli:official'
  entrypoint: anypoint-cli-v4
  args: ["--version"]
